name: ideaz test
favicon: null
layout_spectrum: 0.732719806721434
typography_spectrum: 0.9763535275124013
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.7718303389847279
  lightness: 0.1844459071289748
  saturation: 0.539047225844115
  rhythmicContrast: 0.7973823093343526
purpose: []
